import meta from '../utils/data/meta';

export default async function Head() {
  const data = await meta();

  return (
    <>
      <title>{data.title}</title>
      <meta content='width=device-width, initial-scale=1' name='viewport' />
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </>
  );
}
